export { default as CenteredDiv } from './CenteredDiv';
export { default as ClickImage } from './ClickImage';
export { default as CustomTruncate } from './CustomTruncate';
export { default as DivBottom } from './DivBottom';
export { default as FeedBackCard } from './FeedBackCard';
export { default as FilmListElem } from './FilmListElem';
export { default as RatingSpan } from './RatingSpan';
export { default as Genres } from './Genres';
export { default as StyledButton } from './StyledButton';
